//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_ORDER
    {
        public DELIVERY_ORDER()
        {
            this.DELIVERY_ORDER_DETAIL = new HashSet<DELIVERY_ORDER_DETAIL>();
        }
    
        public int DELORDER_ID { get; set; }
        public int ORDER_ID { get; set; }
        public string DELORDER_CODE { get; set; }
        public Nullable<System.DateTime> DELORDER_DATE { get; set; }
        public string DELORDER_STEP { get; set; }
        public Nullable<int> VEHICLE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual VEHICLE VEHICLE { get; set; }
        public virtual ICollection<DELIVERY_ORDER_DETAIL> DELIVERY_ORDER_DETAIL { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
