//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_MEASURE_WEIGHT
    {
        public EMP_MEASURE_WEIGHT()
        {
            this.EMP_MEASURE_TRANS = new HashSet<EMP_MEASURE_TRANS>();
        }
    
        public int WEIGHT_ID { get; set; }
        public string WEIGHT_NAME { get; set; }
        public decimal WEIGHT_VALUE { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual ICollection<EMP_MEASURE_TRANS> EMP_MEASURE_TRANS { get; set; }
    }
}
