//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_DT_TRANS
    {
        public string PR_BK_NO { get; set; }
        public string PR_RN_NO { get; set; }
        public string PR_YY { get; set; }
        public int PR_SEQ_NO { get; set; }
        public int RAW_ID { get; set; }
        public int RAW_PACK_ID { get; set; }
        public int PO_QTY { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string PR_DT_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual RAW_PRODUCT RAW_PRODUCT { get; set; }
        public virtual RAW_PACK_SIZE RAW_PACK_SIZE { get; set; }
    }
}
