//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR
    {
        public SECTOR()
        {
            this.PROVINCE = new HashSet<PROVINCE>();
            this.STORE = new HashSet<STORE>();
        }
    
        public int SECTOR_ID { get; set; }
        public string SECTOR_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual ICollection<PROVINCE> PROVINCE { get; set; }
        public virtual ICollection<STORE> STORE { get; set; }
    }
}
