//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_RAW_SETTING
    {
        public string STOCK_TRANS_NO { get; set; }
        public string STOCK_TRANS_YY { get; set; }
        public System.DateTime STOCK_TRANS_DATE { get; set; }
        public string REF_DOC_NO1 { get; set; }
        public string REF_DOC_NO2 { get; set; }
        public string REF_DOC_NO3 { get; set; }
        public int VENDOR_ID { get; set; }
        public int RAW_ID { get; set; }
        public string STOCK_RAW_REF_NO1 { get; set; }
        public string STOCK_RAW_REF_NO2 { get; set; }
        public int STOCK_QTY { get; set; }
        public Nullable<int> APPROVE_EMPLOYEE_ID { get; set; }
        public Nullable<System.TimeSpan> SYS_TIME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    }
}
