//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PRODUCT_WITHDRAW_TRANS
    {
        public int TRANS_ID { get; set; }
        public int VEHICLE_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int STORE_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public int COLOR_ID { get; set; }
        public int COLOR_TYPE_ID { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
        public int ORDER_ID { get; set; }
        public string ORDER_CODE { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public int ORDER_DETAIL_ID { get; set; }
        public Nullable<int> PRODUCT_SEQ { get; set; }
        public Nullable<int> PRODUCT_QTY { get; set; }
        public Nullable<int> STOCK_BEFORE { get; set; }
        public Nullable<int> WITHDRAW_QTY { get; set; }
        public Nullable<int> STOCK_AFTER { get; set; }
        public Nullable<int> WITHDRAW_REMAIN_QTY { get; set; }
        public Nullable<int> WITHDRAW_COMPLETE_FLG { get; set; }
        public Nullable<int> APPROVE_EMPLOYEE_ID { get; set; }
        public Nullable<System.TimeSpan> SYS_TIME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        public virtual COLOR_TYPE COLOR_TYPE { get; set; }
        public virtual ORDER ORDER { get; set; }
        public virtual ORDER_DETAIL ORDER_DETAIL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual STORE STORE { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
