//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_DELIVERY_ORDER
    {
        public SUB_DELIVERY_ORDER()
        {
            this.SUB_DELIVERY_ORDER_DETAIL = new HashSet<SUB_DELIVERY_ORDER_DETAIL>();
        }
    
        public int SUB_DELORDER_ID { get; set; }
        public int SUB_DELIND_ID { get; set; }
        public string DELORDER_CODE { get; set; }
        public string DELORDER_SUBCODE { get; set; }
        public Nullable<System.DateTime> DELORDER_DATE { get; set; }
        public Nullable<int> DELORDER_SEQ_NO { get; set; }
        public int STORE_ID { get; set; }
        public int VEHICLE_ID { get; set; }
        public Nullable<decimal> DELORDER_PRICE_TOTAL { get; set; }
        public Nullable<decimal> DELORDER_WEIGHT_TOTAL { get; set; }
        public string DELORDER_STEP { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual STORE STORE { get; set; }
        public virtual SUB_DELIVERY_INDEX SUB_DELIVERY_INDEX { get; set; }
        public virtual ICollection<SUB_DELIVERY_ORDER_DETAIL> SUB_DELIVERY_ORDER_DETAIL { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
