//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_DEAL_CONDITION
    {
        public int VENDOR_ID { get; set; }
        public int VENDEAL_SEQ_NO { get; set; }
        public string VENDEAL_DESC { get; set; }
        public string VENDEAL_PRE_COND_TYPE { get; set; }
        public Nullable<int> VENDEAL_PRE_COND_VALUE { get; set; }
        public string VENDEAL_TYPE_CODE { get; set; }
        public int VENDEAL_TYPE_VALUE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual VENDOR VENDOR { get; set; }
    }
}
