//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONE_DETAIL
    {
        public ZONE_DETAIL()
        {
            this.STORE = new HashSet<STORE>();
        }
    
        public int ZONE_DETAIL_ID { get; set; }
        public Nullable<int> ZONE_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_EMPLOYEE_ID { get; set; }
        public Nullable<int> UPDATE_EMPLOYEE_ID { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<STORE> STORE { get; set; }
        public virtual ZONE ZONE { get; set; }
    }
}
