//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_ORDER_LOG
    {
        public int DELORDER_DETAIL_ID { get; set; }
        public Nullable<int> DELORDER_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> ORDER_DETAIL_ID { get; set; }
        public Nullable<int> PRODUCT_SEQ { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> PRODUCT_QTY { get; set; }
        public Nullable<decimal> PRODUCT_PRICE { get; set; }
        public Nullable<decimal> PRODUCT_TOTAL { get; set; }
        public Nullable<int> COLOR_ID { get; set; }
        public Nullable<int> COLOR_TYPE_ID { get; set; }
        public int PRODUCT_SENT_ROUND { get; set; }
        public Nullable<int> PRODUCT_SENT_QTY { get; set; }
        public Nullable<int> PRODUCT_SENT_REMAIN { get; set; }
        public Nullable<bool> SYE_DEL { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        public virtual COLOR_TYPE COLOR_TYPE { get; set; }
        public virtual DELIVERY_ORDER DELIVERY_ORDER { get; set; }
        public virtual ORDER ORDER { get; set; }
        public virtual ORDER_DETAIL ORDER_DETAIL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
